### ISSUE TITLE
Rcon Issue

### ISSUE THREAD

**Issue by sergiolaguens** [Didstopia/rust-server#104]
Hi, im trying to rcon to my server, i´ve tested in the container too but i received the same error, can anyone help me?

root@b80678415d2b:/# rcon say Hello
RconApp::Relaying RCON command: say Hello
RconApp::Error: Error: Parse Error: Expected HTTP/
    at Socket.socketOnData (_http_client.js:474:22)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  bytesParsed: 0,
  code: 'HPE_INVALID_CONSTANT',
  reason: 'Expected HTTP/',
  rawPacket: <Buffer 88 02 03 e8>
}

**Comment by sergiolaguens** [comment]
on the file, i config the pass with " " but it isnt work... so... 
must be: 
- RUST_RCON_PASSWORD=xxxxxxxx 

not 
- RUST_RCON_PASSWORD="xxxxxxx"
